### ISSUE TITLE
Reload baremetal server failed when to provision it with server id

### ISSUE THREAD

**Issue by zhanggbj** [cloudfoundry-community/bosh-softlayer-baremetal-server#11]
When to reload a baremetal server, it called this api [#L9](https://github.com/cloudfoundry-community/bosh-softlayer-baremetal-server/blob/master/lib/bluemix/api/controllers/baremetal_controller.rb#L8) to provision, but failed with below error

```
{"status":300,"data":{"message":"No available server found, please create new baremetal in the pool 780185"}}
```

This issue could be reproduced by curl as below

```
curl -X PUT -u admin:admin http://{bmp server id}:8080/baremetal/spec/{baremetal server id}/{baremetal stemcell}/{netboot image}
```

It seems that line [#L71](https://github.com/cloudfoundry-community/bosh-softlayer-baremetal-server/blob/master/lib/bluemix/softlayer/baremetal_utils.rb#L71) never got called. It got server info by `SoftLayer::BareMetalServer.server_with_id` but then it returned with nil.

cc @jianqiu  and @mattcui

**Comment by zhanggbj** [comment]
to_server sometimes returns nil instead of the hash in [#L114][1], so added hash definition and return statement.
[1]:https://github.com/cloudfoundry-community/bosh-softlayer-baremetal-server/blob/master/lib/bluemix/softlayer/baremetal_utils.rb#L114

**Comment by maximilien** [comment]
OK closing this.
