### ISSUE TITLE
add some basic docs on how to get started with bmp server

### ISSUE THREAD

**Issue by maximilien** [cloudfoundry-community/bosh-softlayer-baremetal-server#8]
Can we improve the BMP server docs to have some basic getting started

**Comment by zhanggbj** [comment]
Sure, I'll add docs about leveraging bmp server and send PR once done.

**Comment by maximilien** [comment]
Did you add docs? Can you send me PR or link thereof?

**Comment by maximilien** [comment]
OK, I see PR so closing this. Let's move any related discussions there. Thanks.
